### PR TITLE
Skype serviceURL updated!

### PR DESCRIPTION
**Pull request by omergulen**
#15

### CODE REVIEW

**Comment by omergulen** [comment]
I didn't get what you mean, or did you understand what I wanted to change and why?

**Comment by omergulen** [comment]
Still waiting for merge.

**Comment by closingin** [comment]
I don't think this will ever be merged. Why would we put in production a service that points to a preview version of an app ? Because it's a preview, it will constantly change and might break often its Franz integration, whereas the current one is stable.

Just wait for this preview to go live ?

**Comment by omergulen** [comment]
Got it now. I was thinking Franz should provide a new feature to users faster, and instantly that's why I thought would be great but as you said it may not be stable. But is there any chance that Franz can still support this Preview Skype for Web? As a spare service?

**Comment by closingin** [comment]
Maybe in the future, I'd imagine a service setting where you would check a box to enable the preview version !

**Comment by omergulen** [comment]
Or maybe even better you can add your own service? I mean from scratch xd

**Pull request closed without merging**
